### ISSUE TITLE
Sort order of BAM and BED files are different so cannot use -sorted option in bedtools coverage

### ISSUE THREAD

**Issue by s1437643** [arq5x/bedtools#109]
I am trying to get the number of reads mapped to regions in a BED file.

The BAM file is sorted using: 
`samtools sort KAPA.bam KAPA.sorted`

The BED file is sorted using: 
`sort -k1,1 -k2,2 regions.bed > regions.sorted.bed`

I invoke the bedtools coverage command using:
`bedtools coverage -counts -sorted -a regions.bed -b KAPA.sorted.bam`

It runs for a while and then encounters the following error:
`ERROR: chromomsome sort ordering for file KAPA.sorted.bam is inconsistent with other files. Record was:
chr1	3000135	3000185	HISEQ:250:C6E7WANXX:2:2205:18108:58921/1	26	+
3043886`

To my knowledge the two sorting commands must have sorted the files in different orders. Is there a practical work-around for this?

Thanks,
James

**Comment by arq5x** [comment]
Did you accidentally close this, or did you resolve your issue?

**Comment by s1437643** [comment]
I realised you had answered the question before on the Biostars forum. As per your suggestion, I'm converting from BAM to BED and then sorting the BED file.

**Comment by arq5x** [comment]
Well, actually it should work with a BAM file.  Is it possible that your BED file uses chromosome labels such as "1" instead of "chr1"?

Also, you'll want to sort the BED file with -k1,1 -k2,2n. (Note the n).  If your chromosome labeling scheme is the same and it still doesn't work please let us know.

**Comment by s1437643** [comment]
I just double-checked everything was sorted correctly, and tried the same command and I still get the same error.

**Comment by arq5x** [comment]
Could you show the results of the following:

    cut -f 1 my.bed | uniq

And

    samtools view -H my.bam

**Comment by s1437643** [comment]
BED file result:
`chr1
chr10
chr11
chr12
chr13
chr14
chr15
chr16
chr17
chr18
chr19
chr2
chr3
chr4
chr5
chr6
chr7
chr8
chr9
chrM
chrX
chrY
`



BAM file result:

`@HD	VN:1.0	SO:coordinate
@SQ	SN:chr10	LN:130694993
@SQ	SN:chr11	LN:122082543
@SQ	SN:chr12	LN:120129022
@SQ	SN:chr13	LN:120421639
@SQ	SN:chr14	LN:124902244
@SQ	SN:chr15	LN:104043685
@SQ	SN:chr16	LN:98207768
@SQ	SN:chr17	LN:94987271
@SQ	SN:chr18	LN:90702639
@SQ	SN:chr19	LN:61431566
@SQ	SN:chr1	LN:195471971
@SQ	SN:chr2	LN:182113224
@SQ	SN:chr3	LN:160039680
@SQ	SN:chr4	LN:156508116
@SQ	SN:chr5	LN:151834684
@SQ	SN:chr6	LN:149736546
@SQ	SN:chr7	LN:145441459
@SQ	SN:chr8	LN:129401213
@SQ	SN:chr9	LN:124595110
@SQ	SN:chrM	LN:16299
@SQ	SN:chrX	LN:171031299
@SQ	SN:chrY	LN:91744698
@PG	ID:bowtie2	PN:bowtie2	VN:2.2.5	CL:"/home/jashmore/software/bowtie2-2.2.5/bowtie2-align-s --wrapper basic-0 -X 1200 -p 5 -x /home/jashmore/fast/iGenomes/Mus_musculus/UCSC/mm10/Sequence/Bowtie2Index/genome -S ../data/DamKAPA.sam -1 ../data/DamKAPA_1.fastq -2 ../data/DamKAPA_2.fastq"`

**Comment by arq5x** [comment]
Hmm, the orders are clearly different (BAM=chr10,chr11,etc., and BED=chr1,chr10,etc.).

I would have expected samtools to sort the BAM in the same order as the BED.  What tool did you use to sort your BAM file?

**Comment by s1437643** [comment]
I used samtools version 1.2 with the command: `samtools sort DamKAPA.bam DamKAPA.sorted`

**Comment by arq5x** [comment]
Huh.  @jmarshall is this the expected sort order?

**Comment by s1437643** [comment]
I've just checked the header of a colleagues sorted BAM file, which was sorted using samtools 1.1 and the chromosomes are in the 'correct' order i.e. chr1, chr2, chr3. I'll try sorting with samtools 1.1 and see if I can reproduce the correct order.

**Comment by jmarshall** [comment]
Samtools sort doesn't alter the order that the reference chromosomes are in; or equivalently, it doesn't alter the order that the `@SQ` headers appear in.

So the order of the references in the BAM file is (unless there's some fairly unusual software in the pipeline somewhere) the same right from the first time the sequencing data lands in a SAM or BAM file, which is probably in your aligner output.  And probably your aligner generates `@SQ` headers based on how the reference sequences are arranged in the FASTA file from which you built its aligner indices.

So my theory is that the BAM's chr10,chr11,…,chr1,… ordering is the same as in your reference FASTA file.  (And perhaps @s1437643's colleague used a differently-ordered reference?  But I'll be interested to hear how you get on retesting with 1.1.)

**Comment by arq5x** [comment]
Ah, I see. Thanks for the clarification @jmarshall

**Comment by s1437643** [comment]
John was correct about the order of my reference, the @SQ headers were in the same order as the chromosomes in the reference fasta - but I still get the same error when sorting with samtools 1.1

**Comment by arq5x** [comment]
Okay, I think it is going to be easiest if you re-sort your BED to match the BAM.  As of version 2.24 (and thanks to @lindenb , the bedtools `sort` command has a `-faidx` option that will sort a BED file according to the order in a chromosome names.txt file. 

Once sorted this way, you will need to give the coverage command the names.txt file as the `-g` option so that it knows the files are sorted in a custom manner.

**Comment by s1437643** [comment]
Okay, I'll give that a try tomorrow, should the names.txt file contain a chromosome name on each line followed by the size of the chromosome?

**Comment by s1437643** [comment]
I have sorted my BED file according to the order of the chromosomes in the sorted BAM file, however when I pass my names.txt file to bedtools coverage it complains that it has no valid entries. The names.txt is just a single column of chromosome names in the order they appear in the sorted BAM file. Do I need to provide anything else?

**Comment by wkl1990** [comment]
Where can I find the description of the .genomes file? @jma1991

**Comment by sahuno** [comment]
Please my .bam file has chromosomal regions that are not in my .bed file
using this commands I sorted bed file according according to headers of bam file and saved as .txt 
`$ sortBed -i hg19.1Mb.sorted.bed -faidx header_ex54_S7_bedtools2.txt`


then I run bedtools coverage but still didn't work 
`$ bedtools coverage -a hg19.1Mb.sorted.bed -b ex54_S7.sorted.bam -sorted >& out_ex54_S7.sorted_hg19mapping_11252019.bed `

error message 
(```
chr8    126838888       127838887       chr8.124        10      0       0       9999ERROR: chromomsome sort ordering for file ex54_S7.sorted.bam is inconsistent with other files. Record was:
chr10   60056   60094   NB501025:454:H7JNTBGXC:2:22305:25983:5046/1     0       +
```).

Please advice

sam file header
```
@HD	VN:1.6	SO:coordinate
@SQ	SN:chrM	LN:16571
@SQ	SN:chr1	LN:249250621
@SQ	SN:chr2	LN:243199373
@SQ	SN:chr3	LN:198022430
@SQ	SN:chr4	LN:191154276
@SQ	SN:chr5	LN:180915260
@SQ	SN:chr6	LN:171115067
@SQ	SN:chr7	LN:159138663
@SQ	SN:chr8	LN:146364022
@SQ	SN:chr9	LN:141213431
@SQ	SN:chr10	LN:135534747
@SQ	SN:chr11	LN:135006516
@SQ	SN:chr12	LN:133851895
@SQ	SN:chr13	LN:115169878
@SQ	SN:chr14	LN:107349540
@SQ	SN:chr15	LN:102531392
@SQ	SN:chr16	LN:90354753
@SQ	SN:chr17	LN:81195210
@SQ	SN:chr18	LN:78077248
@SQ	SN:chr19	LN:59128983
@SQ	SN:chr20	LN:63025520
@SQ	SN:chr21	LN:48129895
@SQ	SN:chr22	LN:51304566
@SQ	SN:chrX	LN:155270560
@SQ	SN:chrY	LN:59373566
@SQ	SN:chr1_gl000191_random	LN:106433
@SQ	SN:chr1_gl000192_random	LN:547496
@SQ	SN:chr4_ctg9_hap1	LN:590426
@SQ	SN:chr4_gl000193_random	LN:189789
@SQ	SN:chr4_gl000194_random	LN:191469
@SQ	SN:chr6_apd_hap1	LN:4622290
@SQ	SN:chr6_cox_hap2	LN:4795371
@SQ	SN:chr6_dbb_hap3	LN:4610396
@SQ	SN:chr6_mann_hap4	LN:4683263
@SQ	SN:chr6_mcf_hap5	LN:4833398
@SQ	SN:chr6_qbl_hap6	LN:4611984
@SQ	SN:chr6_ssto_hap7	LN:4928567
@SQ	SN:chr7_gl000195_random	LN:182896
@SQ	SN:chr8_gl000196_random	LN:38914
@SQ	SN:chr8_gl000197_random	LN:37175
@SQ	SN:chr9_gl000198_random	LN:90085
@SQ	SN:chr9_gl000199_random	LN:169874
@SQ	SN:chr9_gl000200_random	LN:187035
@SQ	SN:chr9_gl000201_random	LN:36148
@SQ	SN:chr11_gl000202_random	LN:40103
@SQ	SN:chr17_ctg5_hap1	LN:1680828
@SQ	SN:chr17_gl000203_random	LN:37498
@SQ	SN:chr17_gl000204_random	LN:81310
@SQ	SN:chr17_gl000205_random	LN:174588
@SQ	SN:chr17_gl000206_random	LN:41001
@SQ	SN:chr18_gl000207_random	LN:4262
@SQ	SN:chr19_gl000208_random	LN:92689
@SQ	SN:chr19_gl000209_random	LN:159169
@SQ	SN:chr21_gl000210_random	LN:27682
@SQ	SN:chrUn_gl000211	LN:166566
@SQ	SN:chrUn_gl000212	LN:186858
@SQ	SN:chrUn_gl000213	LN:164239
@SQ	SN:chrUn_gl000214	LN:137718
@SQ	SN:chrUn_gl000215	LN:172545
@SQ	SN:chrUn_gl000216	LN:172294
@SQ	SN:chrUn_gl000217	LN:172149
@SQ	SN:chrUn_gl000218	LN:161147
@SQ	SN:chrUn_gl000219	LN:179198
@SQ	SN:chrUn_gl000220	LN:161802
@SQ	SN:chrUn_gl000221	LN:155397
@SQ	SN:chrUn_gl000222	LN:186861
@SQ	SN:chrUn_gl000223	LN:180455
@SQ	SN:chrUn_gl000224	LN:179693
@SQ	SN:chrUn_gl000225	LN:211173
@SQ	SN:chrUn_gl000226	LN:15008
@SQ	SN:chrUn_gl000227	LN:128374
@SQ	SN:chrUn_gl000228	LN:129120
@SQ	SN:chrUn_gl000229	LN:19913
@SQ	SN:chrUn_gl000230	LN:43691
@SQ	SN:chrUn_gl000231	LN:27386
@SQ	SN:chrUn_gl000232	LN:40652
@SQ	SN:chrUn_gl000233	LN:45941
@SQ	SN:chrUn_gl000234	LN:40531
@SQ	SN:chrUn_gl000235	LN:34474
@SQ	SN:chrUn_gl000236	LN:41934
@SQ	SN:chrUn_gl000237	LN:45867
@SQ	SN:chrUn_gl000238	LN:39939
@SQ	SN:chrUn_gl000239	LN:33824
@SQ	SN:chrUn_gl000240	LN:41933
@SQ	SN:chrUn_gl000241	LN:42152
@SQ	SN:chrUn_gl000242	LN:43523
@SQ	SN:chrUn_gl000243	LN:43341
@SQ	SN:chrUn_gl000244	LN:39929
@SQ	SN:chrUn_gl000245	LN:36651
@SQ	SN:chrUn_gl000246	LN:38154
@SQ	SN:chrUn_gl000247	LN:36422
@SQ	SN:chrUn_gl000248	LN:39786
@SQ	SN:chrUn_gl000249	LN:38502
```

Bed file contents
```
chr1
chr10
chr11
chr12
chr13
chr14
chr15
chr16
chr17
chr18
chr19
chr2
chr20
chr21
chr22
chr3
chr4
chr5
chr6
chr7
chr8
chr9
```

**Comment by sahuno** [comment]
solved! 
@kirannbishwa01[ shows a beautiful way to generate the 2-column genome file](https://www.biostars.org/p/70795/)

**Comment by gubrins** [comment]
Heys, I am having similar issues here. When I try to sort the bed file with the .genomes file, my computer rans out of memory (250Gb). Any solution to that?
