### ISSUE TITLE
support for MAF files

### ISSUE THREAD

**Issue by duartemolha** [arq5x/bedtools#115]
Hi...

is there any plan to support MAF files in the future?
https://wiki.nci.nih.gov/display/TCGA/Mutation+Annotation+Format+%28MAF%29+Specification

Many thanks

**Comment by arq5x** [comment]
No plan for MAF, sorry. I would suggest writing a simple conversion script.

**Comment by duartemolha** [comment]
yes... I can convert it easily enough to bed format... it is just that you
loose a lot of the metadata associated with it. I believe there is a
maf2vcf  conversion script .. I'll use that for the time being :)

Thanks

Duarte



[image: --]
Duarte Molha
[image: https://]about.me/duarte
<https://about.me/duarte?promo=email_sig>
