### ISSUE TITLE
Request: Add minimum mapping quality to genomecov

### ISSUE THREAD

**Issue by tantrev** [arq5x/bedtools#117]
Pretty simple, would just be nice if minimum mapping quality could be specified in genomecov.

**Comment by arq5x** [comment]
The prefered method for this would be to use samtools to do the filtering (e.g., only compute coverage for reads with MAPQ>=20):

```
samtools view -q 20 -u aln.bam | bedtools genomecov -ibam - > cov.q20.out
```
