### ISSUE TITLE
Error using genomecov 

### ISSUE THREAD

**Issue by sengoku93** [arq5x/bedtools#129]
Hi,

I am running genomecov in order to take input bedfile and convert to bedgraph file. The plan is to use the converted bedgraph file so I can convert it to bigwig to plot a heatmap of ChipSeq data. However, when I try to use genomecov to get bedgraph:

bedtools genomecov  -bg -i INPUT.bed  -g hg19.genome

or 
bedtools genomecov  -bg -i BCL6.bed  -g hg19.chrom.sizes

I end up getting the same error:
Input error: Chromosome chr17_random found in your input file but not in your genome file.

Any advice would be appreciated. Thank you!

**Comment by arq5x** [comment]
This is telling you that there are data entries for chr17_random in INPUT.bed or BCL6.bed but the length of that chromosome is not described in either hg19.genome or hg19.chrom.sizes. You will need to have all chromosome that are in your input (-i) represented in the genome (-g) file.
