### ISSUE TITLE
Bedtools subtract misses whole chromosomes when -sorted -g ref.dict

### ISSUE THREAD

**Issue by nh13** [arq5x/bedtools#142]
If I leave out the `-sorted -g ref.dict` options it works just fine.

The `-b` file is missing some chromosomes from the `-a` file.  I cannot share the BED files as they are confidential, but I'll keep trying to find a small reproducible test case.  Version 2.27.1

**Comment by arq5x** [comment]
Could you move this to the [bedtools2](https://github.com/arq5x/bedtools) repo?  Also, are the BED files in the same chrom order as the chroms in the -g file?
